server-port: 8081
db-name: local_db
db-host: localhost
db-user: local_user
db-pass: local_pass

server:
  port: ${server-port}

spring:
  application:
    name: cards-api
  flyway:
    baseline-on-migrate: true
  datasource:
    username: ${db-user}
    password: ${db-pass}
    url: jdbc:h2:mem:${db-name};MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true # https://github.com/pgjdbc/pgjdbc/issues/1102#issuecomment-398036270
    open-in-view: false